/* eslint-disable max-lines -- fixture file: one Trip object per trip, length grows with data */
import { Trip } from './models/trip.model';

/**
 * UI fixtures transcribed from the Shipping Prototype trips list and the
 * trip-details / departure-summary modals (screenshots of the live
 * prototype, 2026-07-21). Revenue/expense/profit figures are display data
 * only until the backend owns the calculation (same convention as
 * `SHIPMENT_FIXTURES`) — they were reverse-engineered from the prototype
 * screenshots and are internally consistent with the currency totals of the
 * shipments each trip carries (see `shipments.data.ts`, ids grouped by
 * `tripNumber`).
 */
export const TRIP_FIXTURES: readonly Trip[] = [
  {
    id: 1,
    tripNo: 'TR-2024-001',
    waybillNo: 'WB-2024-001',
    status: 'inProgress',
    originCity: 'القاهرة',
    destinationCountry: 'الكويت',
    destinationCity: 'الكويت',
    waybillCreatedDate: null,
    tripStartDate: '2024-01-15',
    expectedDeparture: '2024-01-15',
    actualDeparture: '2024-01-15 08:00',
    expectedArrival: '2024-01-18',
    actualArrival: null,
    assignmentMode: 'internal',
    driverName: 'يوسف الحناوي',
    truckPlate: 'ق ط ر ١٢٣٤',
    driverAdvance: 5000,
    driverAdvanceIssued: true,
    shipmentIds: [1, 2, 3],
    totalRevenue: 111003,
    totalExpenses: 4306,
    fieldOps: {
      durationLabel: '4 س 6 د',
      drivingTimeLabel: '3 س 43 د',
      fuelTimeLabel: '23 د',
      stopsCount: 1,
      idleTimeLabel: '0 د',
      avgDeliveryTimeLabel: '—',
      arrivalPerformance: 'unknown',
      distanceKmLabel: '—',
    },
    activityLog: [
      {
        message: 'تم تأكيد المغادرة',
        detail: null,
        actor: 'يوسف الحناوي',
        time: '10:16 2026-07-21',
        icon: '🛫',
      },
      {
        message: 'بدء التوقف · وقود',
        detail: 'محطة وقود — طريق السويس',
        actor: 'يوسف الحناوي',
        time: '09:53 2026-07-21',
        icon: '⏸',
      },
      {
        message: 'انطلقت الرحلة',
        detail: 'مستودع الرماح — مدينة نصر، القاهرة',
        actor: 'يوسف الحناوي',
        time: '08:18 2026-07-21',
        icon: '🚛',
      },
      {
        message: 'تم استلام الشحنات',
        detail: 'مستودع الرماح — مدينة نصر، القاهرة · تم استلام 3 شحنات ومطابقتها',
        actor: 'يوسف الحناوي',
        time: '08:13 2026-07-21',
        icon: '📦',
      },
      {
        message: 'تم قبول الرحلة',
        detail: null,
        actor: 'يوسف الحناوي',
        time: '08:08 2026-07-21',
        icon: '🤝',
      },
    ],
    collections: [
      {
        time: '07:50 2024-01-15',
        shipmentNo: 'SH-001',
        customerName: 'أحمد عبد الله',
        amount: 2000,
        currency: 'EGP',
        paymentMethod: 'نقدي',
        location: 'مستودع القاهرة',
        collectedBy: 'يوسف الحناوي',
      },
      {
        time: '13:20 2024-01-17',
        shipmentNo: 'SH-002',
        customerName: 'شركة النيل للاستيراد والتصدير',
        amount: 350,
        currency: 'KWD',
        paymentMethod: 'نقدي',
        location: 'حولي - الكويت',
        collectedBy: 'يوسف الحناوي',
      },
    ],
    expenses: [
      {
        category: 'وقود',
        icon: '⛽',
        amount: 1200,
        currency: 'EGP',
        date: '2024-01-15',
        driver: 'يوسف الحناوي',
        note: 'محطة القاهرة',
      },
      {
        category: 'رسوم حدود',
        icon: '🛂',
        amount: 450,
        currency: 'EGP',
        date: '2024-01-16',
        driver: 'يوسف الحناوي',
        note: 'ميناء الإسكندرية',
      },
      {
        category: 'طعام',
        icon: '🍔',
        amount: 180,
        currency: 'EGP',
        date: '2024-01-16',
        driver: 'يوسف الحناوي',
        note: '—',
      },
      {
        category: 'جمارك',
        icon: '🛃',
        amount: 520,
        currency: 'EGP',
        date: '2024-01-17',
        driver: 'يوسف الحناوي',
        note: '—',
      },
      {
        category: 'مواقف وانتظار',
        icon: '🅿️',
        amount: 12,
        currency: 'KWD',
        date: '2024-01-16',
        driver: 'يوسف الحناوي',
        note: 'مواقف الشاحنات — الكويت',
      },
    ],
  },
  {
    id: 2,
    tripNo: 'TR-2024-002',
    waybillNo: 'WB-2024-002',
    status: 'inProgress',
    originCity: 'الإسكندرية',
    destinationCountry: 'السعودية',
    destinationCity: 'السعودية',
    waybillCreatedDate: null,
    tripStartDate: '2024-01-16',
    expectedDeparture: '2024-01-16',
    actualDeparture: '2024-01-16 07:30',
    expectedArrival: '2024-01-20',
    actualArrival: null,
    assignmentMode: 'internal',
    driverName: 'حسن المغربي',
    truckPlate: 'ص ع د ٥٦٧٨',
    driverAdvance: 6000,
    driverAdvanceIssued: true,
    shipmentIds: [4, 5, 6, 7],
    totalRevenue: 175006,
    totalExpenses: 5205,
    fieldOps: {
      durationLabel: '5 س 13 د',
      drivingTimeLabel: '4 س 13 د',
      fuelTimeLabel: '22 د',
      stopsCount: 2,
      idleTimeLabel: '38 د',
      avgDeliveryTimeLabel: '—',
      arrivalPerformance: 'unknown',
      distanceKmLabel: '—',
    },
    activityLog: [
      {
        message: 'بدء التوقف · جمارك',
        detail: 'المعبر الحدودي — بانتظار موافقة الجمارك على المعبر',
        actor: 'حسن المغربي',
        time: '11:48 2026-07-21',
        icon: '⏸',
      },
      {
        message: 'استئناف الرحلة',
        detail: null,
        actor: 'حسن المغربي',
        time: '09:45 2026-07-21',
        icon: '▶️',
      },
      {
        message: 'بدء التوقف · وقود',
        detail: 'طريق القاهرة–السويس الصحراوي — تعبئة وقود',
        actor: 'حسن المغربي',
        time: '09:23 2026-07-21',
        icon: '⏸',
      },
      {
        message: 'انطلقت الرحلة',
        detail: 'مستودع الإسكندرية — سموحة',
        actor: 'حسن المغربي',
        time: '07:13 2026-07-21',
        icon: '🚛',
      },
      {
        message: 'تم استلام الشحنات',
        detail: null,
        actor: 'حسن المغربي',
        time: '07:08 2026-07-21',
        icon: '📦',
      },
    ],
    collections: [],
    expenses: [
      {
        category: 'وقود',
        icon: '⛽',
        amount: 1850,
        currency: 'EGP',
        date: '2024-01-16',
        driver: 'حسن المغربي',
        note: 'محطة الإسكندرية',
      },
      {
        category: 'رسوم حدود',
        icon: '🛂',
        amount: 900,
        currency: 'EGP',
        date: '2024-01-16',
        driver: 'حسن المغربي',
        note: 'المعبر الحدودي',
      },
      {
        category: 'جمارك',
        icon: '🛃',
        amount: 1655,
        currency: 'EGP',
        date: '2024-01-17',
        driver: 'حسن المغربي',
        note: '—',
      },
      {
        category: 'طعام وإقامة',
        icon: '🍔',
        amount: 800,
        currency: 'EGP',
        date: '2024-01-17',
        driver: 'حسن المغربي',
        note: '—',
      },
    ],
  },
  {
    id: 3,
    tripNo: 'TR-2024-003',
    waybillNo: 'WB-2024-003',
    status: 'completed',
    originCity: 'القاهرة',
    destinationCountry: 'الإمارات',
    destinationCity: 'الإمارات',
    waybillCreatedDate: null,
    tripStartDate: '2024-01-10',
    expectedDeparture: '2024-01-10',
    actualDeparture: '2024-01-10 09:00',
    expectedArrival: '2024-01-14',
    actualArrival: '2024-01-14 16:00',
    assignmentMode: 'internal',
    driverName: 'طارق سليمان',
    truckPlate: 'ر س ط ٣٤٥٦',
    driverAdvance: 4500,
    driverAdvanceIssued: true,
    shipmentIds: [8, 9, 10],
    totalRevenue: 124000,
    totalExpenses: 2960,
    fieldOps: {
      durationLabel: '105 س 30 د',
      drivingTimeLabel: '94 س 3 د',
      fuelTimeLabel: '27 د',
      stopsCount: 3,
      idleTimeLabel: '3 س 30 د',
      avgDeliveryTimeLabel: '1 س 22 د',
      arrivalPerformance: 'onTime',
      distanceKmLabel: '3,400 كم',
    },
    activityLog: [
      {
        message: 'اكتملت الرحلة',
        detail: 'الشارقة، الإمارات',
        actor: 'طارق سليمان',
        time: '18:30 2024-01-14',
        icon: '✅',
      },
      {
        message: 'تم تسليم الشحنة SH-010',
        detail: 'الشارقة، الإمارات · تم التسليم كاملاً',
        actor: 'طارق سليمان',
        time: '18:05 2024-01-14',
        icon: '📦',
      },
      {
        message: 'تم تسليم الشحنة SH-009',
        detail: 'أبوظبي، الإمارات · تم التسليم كاملاً',
        actor: 'طارق سليمان',
        time: '17:20 2024-01-14',
        icon: '📦',
      },
      {
        message: 'تم تسليم الشحنة SH-008',
        detail: 'دبي، الإمارات · سلّمت بعجز 160 قطعة',
        actor: 'طارق سليمان',
        time: '16:40 2024-01-14',
        icon: '📦',
      },
    ],
    collections: [
      {
        time: '18:10 2024-01-14',
        shipmentNo: 'SH-010',
        customerName: 'عمر الشناوي',
        amount: 480,
        currency: 'USD',
        paymentMethod: 'نقدي',
        location: 'الشارقة - الإمارات',
        collectedBy: 'طارق سليمان',
      },
      {
        time: '17:25 2024-01-14',
        shipmentNo: 'SH-009',
        customerName: 'سارة منصور',
        amount: 1040,
        currency: 'USD',
        paymentMethod: 'نقدي',
        location: 'أبوظبي - الإمارات',
        collectedBy: 'طارق سليمان',
      },
    ],
    expenses: [
      {
        category: 'وقود',
        icon: '⛽',
        amount: 1450,
        currency: 'EGP',
        date: '2024-01-11',
        driver: 'طارق سليمان',
        note: '—',
      },
      {
        category: 'رسوم حدود',
        icon: '🛂',
        amount: 780,
        currency: 'EGP',
        date: '2024-01-12',
        driver: 'طارق سليمان',
        note: '—',
      },
      {
        category: 'طعام',
        icon: '🍔',
        amount: 340,
        currency: 'EGP',
        date: '2024-01-13',
        driver: 'طارق سليمان',
        note: '—',
      },
      {
        category: 'مواقف وانتظار',
        icon: '🅿️',
        amount: 390,
        currency: 'EGP',
        date: '2024-01-13',
        driver: 'طارق سليمان',
        note: '—',
      },
    ],
  },
  {
    id: 4,
    tripNo: 'TR-2024-004',
    waybillNo: 'WB-2024-004',
    status: 'planned',
    originCity: 'القاهرة',
    destinationCountry: 'قطر',
    destinationCity: 'قطر',
    waybillCreatedDate: null,
    tripStartDate: '2024-01-13',
    expectedDeparture: '2024-01-13',
    actualDeparture: null,
    expectedArrival: '2024-01-17',
    actualArrival: null,
    assignmentMode: 'internal',
    driverName: 'عبد الله رشاد',
    truckPlate: 'ل م ن ٩٠١٢',
    driverAdvance: 3000,
    driverAdvanceIssued: false,
    shipmentIds: [11, 12],
    totalRevenue: 2000,
    totalExpenses: 0,
    fieldOps: null,
    activityLog: [
      {
        message: 'الرحلة أُنشئت',
        detail: null,
        actor: 'طارق منصور',
        time: '2024-01-12',
        icon: '🗓',
      },
    ],
    collections: [],
    expenses: [],
  },
  {
    id: 5,
    tripNo: 'TR-2024-005',
    waybillNo: 'WB-2024-005',
    status: 'closed',
    originCity: 'الإسكندرية',
    destinationCountry: 'الكويت',
    destinationCity: 'الكويت',
    waybillCreatedDate: null,
    tripStartDate: '2024-01-09',
    expectedDeparture: '2024-01-09',
    actualDeparture: '2024-01-09 07:00',
    expectedArrival: '2024-01-13',
    actualArrival: '2024-01-14 17:30',
    assignmentMode: 'internal',
    driverName: 'يوسف الحناوي',
    truckPlate: 'ق ط ر ١٢٣٤',
    driverAdvance: 4000,
    driverAdvanceIssued: true,
    shipmentIds: [13, 14, 15],
    totalRevenue: 146048,
    totalExpenses: 4970,
    fieldOps: {
      durationLabel: '105 س 30 د',
      drivingTimeLabel: '104 س 30 د',
      fuelTimeLabel: '25 د',
      stopsCount: 2,
      idleTimeLabel: '1 س 0 د',
      avgDeliveryTimeLabel: '1 س 22 د',
      arrivalPerformance: 'onTime',
      distanceKmLabel: '4,200 كم',
    },
    activityLog: [
      {
        message: 'اكتملت الرحلة',
        detail: 'مدينة الكويت',
        actor: 'يوسف الحناوي',
        time: '17:30 2024-01-09',
        icon: '✅',
      },
      {
        message: 'تم تسليم الشحنة SH-015',
        detail: 'مدينة الكويت · تم التسليم',
        actor: 'يوسف الحناوي',
        time: '17:00 2024-01-09',
        icon: '📦',
      },
      {
        message: 'تم تسليم الشحنة SH-014',
        detail: 'مدينة الكويت · تم التسليم',
        actor: 'يوسف الحناوي',
        time: '16:20 2024-01-09',
        icon: '📦',
      },
      {
        message: 'تم تسليم الشحنة SH-013',
        detail: 'مدينة الكويت · سلّمت بعجز 200 قطعة',
        actor: 'يوسف الحناوي',
        time: '15:45 2024-01-09',
        icon: '📦',
      },
    ],
    collections: [
      {
        time: '17:35 2024-01-09',
        shipmentNo: 'SH-015',
        customerName: 'شركة الفجر للملابس الجاهزة',
        amount: 258,
        currency: 'KWD',
        paymentMethod: 'نقدي',
        location: 'حولي - الكويت',
        collectedBy: 'يوسف الحناوي',
      },
      {
        time: '16:25 2024-01-09',
        shipmentNo: 'SH-014',
        customerName: 'علي الدسوقي',
        amount: 190,
        currency: 'KWD',
        paymentMethod: 'نقدي',
        location: 'الجهراء - الكويت',
        collectedBy: 'يوسف الحناوي',
      },
    ],
    expenses: [
      {
        category: 'وقود',
        icon: '⛽',
        amount: 2100,
        currency: 'EGP',
        date: '2024-01-09',
        driver: 'يوسف الحناوي',
        note: '—',
      },
      {
        category: 'رسوم حدود',
        icon: '🛂',
        amount: 620,
        currency: 'EGP',
        date: '2024-01-10',
        driver: 'يوسف الحناوي',
        note: '—',
      },
      {
        category: 'جمارك',
        icon: '🛃',
        amount: 900,
        currency: 'EGP',
        date: '2024-01-10',
        driver: 'يوسف الحناوي',
        note: '—',
      },
      {
        category: 'طعام وإقامة',
        icon: '🍔',
        amount: 1350,
        currency: 'EGP',
        date: '2024-01-11',
        driver: 'يوسف الحناوي',
        note: '—',
      },
    ],
  },
  {
    id: 6,
    tripNo: 'TR-2024-006',
    waybillNo: 'WB-2024-006',
    status: 'planned',
    originCity: 'القاهرة',
    destinationCountry: 'البحرين',
    destinationCity: 'البحرين',
    waybillCreatedDate: null,
    tripStartDate: '2024-01-18',
    expectedDeparture: '2024-01-18',
    actualDeparture: null,
    expectedArrival: '2024-01-22',
    actualArrival: null,
    assignmentMode: 'internal',
    driverName: 'إبراهيم سعيد',
    truckPlate: 'ل م ن ٩٠١٢',
    driverAdvance: 2500,
    driverAdvanceIssued: false,
    shipmentIds: [16, 17],
    totalRevenue: 1480,
    totalExpenses: 0,
    fieldOps: null,
    activityLog: [
      {
        message: 'الرحلة أُنشئت',
        detail: null,
        actor: 'طارق منصور',
        time: '2024-01-17',
        icon: '🗓',
      },
    ],
    collections: [],
    expenses: [],
  },
];
