import { TripManifestData, WaybillBatchData, ReceiptBatchData } from '@shared/ui/print-dialogs';

export const MANIFEST_FIXTURE: TripManifestData = {
  manifestNo: 'MF-2024-001',
  tripNo: 'TR-2024-001',
  loadingDate: '2024-01-15',
  warehouse: 'القاهرة',
  destination: 'الكويت',
  status: 'جارية',
  truckPlate: 'ق ط ر ١٢٣٤',
  truckModel: 'مرسيدس أكتروس 2022',
  truckOwner: 'مؤسسة الرماح',
  truckCapacityKg: 20000,
  driverName: 'يوسف الحناوي',
  driverPhone: '+201112220001',
  driverLicense: 'EG-123456',
  driverPassport: 'A1234567',
  shipments: [
    {
      shipmentNo: 'SH-001',
      clientName: 'أحمد عبد الله — شركة الخليج للتجارة',
      destinationCity: 'الكويت',
      packages: 10,
      packageType: 'كرتون',
      goodsCategory: 'ملابس',
      weightKg: 500,
      volumeM3: '—',
      dimensionsCm: '—',
      notes: '—',
    },
    {
      shipmentNo: 'SH-002',
      clientName: 'شركة النيل للاستيراد والتصدير — مؤسسة المنار',
      destinationCity: 'حولي',
      packages: 25,
      packageType: 'كرتون',
      goodsCategory: 'ملابس',
      weightKg: 1200,
      volumeM3: '—',
      dimensionsCm: '—',
      notes: 'قابل للكسر',
    },
    {
      shipmentNo: 'SH-003',
      clientName: 'محمود السيد — تاجر تجزئة',
      destinationCity: 'الجهراء',
      packages: 8,
      packageType: 'صندوق بلاستيك',
      goodsCategory: 'أخرى',
      weightKg: 320,
      volumeM3: '—',
      dimensionsCm: '—',
      notes: '—',
    },
  ],
  totalRevenue: '≈ 111,003 ج.م',
};

export const WAYBILL_BATCH_FIXTURE: WaybillBatchData = {
  tripNo: 'TR-2024-004',
  waybills: [
    {
      waybillNo: 'WB-011',
      date: '2024-01-13',
      shipper: 'شركة الأهرام للإلكترونيات',
      consignee: 'موزع قطري',
      originCity: 'القاهرة',
      destinationCity: 'قطر - الدوحة',
      packages: 14,
      weightTon: 0.7,
      packageType: 'كرتون',
      goodsCategory: 'مواد غذائية',
      goodsDescription: 'مواد غذائية معلبة',
      quantity: 168,
      volumeM3: '—',
      dimensionsCm: '—',
      freightFee: '4,357 ر.ق',
      freightBalance: '4,357 ر.ق',
      driverAdvance: '3,000 ج.م',
      notes: '',
      truckPlate: 'ل م ن ٩٠١٢',
      truckModel: 'مان TGX',
      truckColor: 'أحمر',
      truckYear: '2023',
      truckCapacity: '22,000 كجم',
      truckOwner: 'مؤسسة الرماح',
      driverName: 'عبد الله رشاد',
      driverPhone: '+201112220005',
      driverNationality: 'مصري',
      driverNationalId: '—',
      driverPassport: 'E5678901',
      driverPassportIssue: 'الإسكندرية 2023',
      driverLicense: 'EG-567890',
      driverLicenseExpiry: '—',
      driverAddress: 'الإسكندرية - المنتزه',
      ownerAddress: '—',
      ownerNationality: 'مصري',
      managerName: 'م/ رماح عبد الحليم',
    },
    {
      waybillNo: 'WB-012',
      date: '2024-01-13',
      shipper: 'ناصر حسن',
      consignee: 'محل الريان',
      originCity: 'القاهرة',
      destinationCity: 'قطر - الريان',
      packages: 9,
      weightTon: 0.42,
      packageType: 'كرتون',
      goodsCategory: 'معدات طبية',
      goodsDescription: 'مستلزمات طبية',
      quantity: 108,
      volumeM3: '—',
      dimensionsCm: '—',
      freightFee: '2,786 ر.ق',
      freightBalance: '2,786 ر.ق',
      driverAdvance: '3,000 ج.م',
      notes: 'عاجل',
      truckPlate: 'ل م ن ٩٠١٢',
      truckModel: 'مان TGX',
      truckColor: 'أحمر',
      truckYear: '2023',
      truckCapacity: '22,000 كجم',
      truckOwner: 'مؤسسة الرماح',
      driverName: 'عبد الله رشاد',
      driverPhone: '+201112220005',
      driverNationality: 'مصري',
      driverNationalId: '—',
      driverPassport: 'E5678901',
      driverPassportIssue: 'الإسكندرية 2023',
      driverLicense: 'EG-567890',
      driverLicenseExpiry: '—',
      driverAddress: 'الإسكندرية - المنتزه',
      ownerAddress: '—',
      ownerNationality: 'مصري',
      managerName: 'م/ رماح عبد الحليم',
    },
  ],
};

export const RECEIPT_BATCH_FIXTURE: ReceiptBatchData = {
  tripNo: 'TR-2024-004',
  receipts: [
    {
      receiptNo: 'RR-2024-00011',
      shipmentNo: 'SH-011',
      date: '2024-01-13',
      dayOfWeek: 'السبت',
      senderName: 'شركة الأهرام للإلكترونيات',
      senderPhone: '+201112233445',
      senderAddress: 'الجيزة - مصر',
      consigneeName: 'موزع قطري',
      consigneePhone: '',
      consigneeAddress: 'قطر - الدوحة',
      packages: 14,
      weightKg: 700,
      packageType: 'كرتون',
      quantity: 168,
      goodsCategory: 'مواد غذائية',
      volumeM3: '—',
      dimensionsCm: '—',
      shippingPrice: '4,357 ر.ق',
      goodsDescription: 'مواد غذائية معلبة',
      notes: '',
      warehouse: 'القاهرة',
      warehousekeeper: 'سلمى عبد الله',
    },
    {
      receiptNo: 'RR-2024-00012',
      shipmentNo: 'SH-012',
      date: '2024-01-13',
      dayOfWeek: 'السبت',
      senderName: 'ناصر حسن',
      senderPhone: '+201223344556',
      senderAddress: 'الفيوم - مصر',
      consigneeName: 'محل الريان',
      consigneePhone: '',
      consigneeAddress: 'قطر - الريان',
      packages: 9,
      weightKg: 420,
      packageType: 'كرتون',
      quantity: 108,
      goodsCategory: 'معدات طبية',
      volumeM3: '—',
      dimensionsCm: '—',
      shippingPrice: '2,786 ر.ق',
      goodsDescription: 'مستلزمات طبية',
      notes: 'عاجل',
      warehouse: 'القاهرة',
      warehousekeeper: 'سلمى عبد الله',
    },
  ],
};
