import { Customer } from './models/customer.model';

/**
 * UI fixtures transcribed from the Shipping Prototype customer list.
 * Financial values are display data only until the backend owns calculations.
 */
export const CUSTOMER_FIXTURES: readonly Customer[] = [
  {
    id: 1,
    name: 'أحمد عبد الله',
    phone: '+201001234567',
    email: 'ahmed@example.com',
    city: 'القاهرة',
    governorate: 'القاهرة',
    country: 'مصر',
    notes: '',
    shipmentCount: 2,
    revenue: 59948,
    balance: 50331,
  },
  {
    id: 2,
    name: 'شركة النيل للاستيراد والتصدير',
    phone: '+201112345678',
    email: 'alnile@example.com',
    city: 'الجيزة',
    governorate: 'الجيزة',
    country: 'مصر',
    notes: 'عميل منتظم',
    shipmentCount: 2,
    revenue: 104028,
    balance: 86587,
  },
  {
    id: 3,
    name: 'محمود السيد',
    phone: '+201223456789',
    email: 'm.elsayed@example.com',
    city: 'الإسكندرية',
    governorate: 'الإسكندرية',
    country: 'مصر',
    notes: '',
    shipmentCount: 1,
    revenue: 21027,
    balance: 14670,
  },
  {
    id: 4,
    name: 'مؤسسة الدلتا التجارية',
    phone: '+201004567890',
    email: 'delta@example.com',
    city: 'المنصورة',
    governorate: 'الدقهلية',
    country: 'مصر',
    notes: '',
    shipmentCount: 2,
    revenue: 80002,
    balance: 66495,
  },
  {
    id: 5,
    name: 'فاطمة إبراهيم',
    phone: '+201115678901',
    email: 'fatma@example.com',
    city: 'طنطا',
    governorate: 'الغربية',
    country: 'مصر',
    notes: '',
    shipmentCount: 2,
    revenue: 79999,
    balance: 76398,
  },
  {
    id: 6,
    name: 'شركة المستقبل للتجارة',
    phone: '+201226789012',
    email: 'future@example.com',
    city: 'القاهرة',
    governorate: 'القاهرة',
    country: 'مصر',
    notes: '',
    shipmentCount: 2,
    revenue: 99934,
    balance: 57408,
  },
  {
    id: 7,
    name: 'خالد عبد الرحمن',
    phone: '+201007890123',
    email: 'khaled@example.com',
    city: 'بورسعيد',
    governorate: 'بورسعيد',
    country: 'مصر',
    notes: '',
    shipmentCount: 2,
    revenue: 64997,
    balance: 25194,
  },
  {
    id: 8,
    name: 'مجموعة النصر',
    phone: '+201118901234',
    email: 'elnasr@example.com',
    city: 'الإسكندرية',
    governorate: 'الإسكندرية',
    country: 'مصر',
    notes: 'شحنات تجارية',
    shipmentCount: 2,
    revenue: 80994,
    balance: 56994,
  },
  {
    id: 9,
    name: 'سارة منصور',
    phone: '+201229012345',
    email: 'sara@example.com',
    city: 'أسيوط',
    governorate: 'أسيوط',
    country: 'مصر',
    notes: '',
    shipmentCount: 1,
    revenue: 52000,
    balance: 12000,
  },
  {
    id: 10,
    name: 'عمر الشناوي',
    phone: '+201001122334',
    email: 'omar@example.com',
    city: 'القاهرة',
    governorate: 'القاهرة',
    country: 'مصر',
    notes: '',
    shipmentCount: 2,
    revenue: 65000,
    balance: 15000,
  },
  {
    id: 11,
    name: 'شركة الأهرام للإلكترونيات',
    phone: '+201112233445',
    email: 'ahram@example.com',
    city: 'الجيزة',
    governorate: 'الجيزة',
    country: 'مصر',
    notes: '',
    shipmentCount: 1,
    revenue: 61000,
    balance: 22000,
  },
  {
    id: 12,
    name: 'ناصر حسن',
    phone: '+201223344556',
    email: 'nasser@example.com',
    city: 'الفيوم',
    governorate: 'الفيوم',
    country: 'مصر',
    notes: '',
    shipmentCount: 1,
    revenue: 39000,
    balance: 18000,
  },
  {
    id: 13,
    name: 'مؤسسة الربيع',
    phone: '+201004455667',
    email: 'rabie@example.com',
    city: 'دمياط',
    governorate: 'دمياط',
    country: 'مصر',
    notes: '',
    shipmentCount: 1,
    revenue: 73000,
    balance: 25000,
  },
  {
    id: 14,
    name: 'علي الدسوقي',
    phone: '+201115566778',
    email: 'ali@example.com',
    city: 'الزقازيق',
    governorate: 'الشرقية',
    country: 'مصر',
    notes: '',
    shipmentCount: 1,
    revenue: 31000,
    balance: 20000,
  },
  {
    id: 15,
    name: 'شركة الفجر للملابس الجاهزة',
    phone: '+201226677889',
    email: 'fajr@example.com',
    city: 'المحلة الكبرى',
    governorate: 'الغربية',
    country: 'مصر',
    notes: '',
    shipmentCount: 1,
    revenue: 42000,
    balance: 30000,
  },
  {
    id: 16,
    name: 'سمير عبد الله',
    phone: '+201009988776',
    email: '',
    city: 'القاهرة',
    governorate: 'القاهرة',
    country: 'مصر',
    notes: 'أُنشئ من شاشة الاستلام',
    shipmentCount: 1,
    revenue: 9000,
    balance: 26000,
  },
  {
    id: 17,
    name: 'وليد كرم',
    phone: '+201557788990',
    email: '',
    city: 'الجيزة',
    governorate: 'الجيزة',
    country: 'مصر',
    notes: 'أُنشئ من شاشة الاستلام',
    shipmentCount: 1,
    revenue: 26000,
    balance: 20076,
  },
];
