import { Truck } from './models/truck.model';
import { TRUCK_FIXTURES_EXTRA } from './trucks.data.extra';

// ── Trucks 1 & 2 ─────────────────────────────────────────────────────────────
// Trucks 3 & 4 live in trucks.data.extra.ts to stay within the 400-line limit.
const TRUCK_FIXTURES_BASE: readonly Truck[] = [
  {
    id: 1,
    plateNumber: 'ق ط ر ١٢٣٤',
    vehicleType: 'مرسيدس أكتروس',
    vehicleModel: '2022',
    vehicleColor: 'أبيض',
    capacityKg: 20000,
    transportType: 'owned',
    vehicleLicenseNo: 'LIC-001',
    driverName: 'يوسف الحناوي',
    licenseExpiry: '2027-04-12',
    insurance: { count: 2, nearestExpiry: '2026-08-01', state: 'expiringSoon' },
    maintenanceCostEgp: 19950,
    status: 'onRoad',
    ownerName: 'مؤسسة الرماح',
    ownerPhone: '+966501234567',
    ownerAddress: 'الرياض، المملكة العربية السعودية',
    stats: {
      currentDriver: 'يوسف الحناوي',
      currentTrip: 'TR-2024-001',
      totalTrips: 2,
      tripsThisMonth: 0,
      distanceKm: '4,200 كم',
      revenue: '≈ 257,051 ج.م',
      expenses: '≈ 9,276 ج.م',
      maintenanceCost: '≈ 19,950 ج.م',
      fuelCost: '—',
      fines: 0,
      thisMonthCost: '≈ 0 ج.م',
      thisYearCost: '≈ 1,450 ج.م',
      currentMileageKm: '182,000 كم',
      openReminders: 0,
      renewalCount: 4,
      renewalBannerText:
        'انتهاء تأمين الشاحنة ق ط ر ١٢٣٤ — شركة مصر للتأمين (مصر) · خلال 16 يوم متبقٍ · تأمين — ق ط ر ١٢٣٤ · خلال 16 يوم متبقٍ · تغيير زيت — ق ط ر ١٢٣٤ · خلال 40 يوم متبقٍ',
      renewalBannerTextEn:
        '🛡 Truck insurance expiry ق ط ر ١٢٣٤ — شركة مصر للتأمين (مصر) · in 16 days left · Insurance — ق ط ر ١٢٣٤ · in 16 days left · Oil Change — ق ط ر ١٢٣٤ · in 40 days left',
      currentTripNo: 'TR-2024-001',
      currentTripShipments: 3,
    },
    vehicleRecords: [
      {
        id: 101,
        date: '2026-05-28',
        recordType: 'oilChange',
        recordTypeLabel: '🛢 تغيير زيت',
        mileageKm: 182000,
        costEgp: 1450,
        costDisplay: '1,450 ج.م',
        supplier: 'مركز خدمة مرسيدس',
        invoiceNo: 'MNT-1101',
        nextServiceDate: '2026-08-25',
        status: 'done',
        notes: 'زيت + فلتر',
      },
      {
        id: 102,
        date: '2025-08-01',
        recordType: 'insurance',
        recordTypeLabel: '🛡 تأمين',
        mileageKm: null,
        costEgp: 18500,
        costDisplay: '18,500 ج.م',
        supplier: 'شركة مصر للتأمين',
        invoiceNo: 'INS-7742',
        nextServiceDate: '2026-08-01',
        status: 'done',
        notes: 'وثيقة شاملة سنوية',
      },
    ],
    insuranceRecords: [
      {
        id: 201,
        insuranceCompany: 'الخليج للتأمين — الكويت',
        country: 'الكويت',
        policyNo: 'KW-88410',
        coverageType: 'ضد الغير',
        issueDate: '2025-10-01',
        expiryDate: '2026-10-01',
        costDisplay: '220 د.ك',
        state: 'active',
        attachment: '',
        notes: 'تغطية داخل أراضي الكويت',
      },
      {
        id: 202,
        insuranceCompany: 'شركة مصر للتأمين',
        country: 'مصر',
        policyNo: 'EG-INS-7742',
        coverageType: 'شامل',
        issueDate: '2025-08-01',
        expiryDate: '2026-08-01',
        costDisplay: '18,500 ج.م',
        state: 'expiringSoon',
        attachment: '📎',
        notes: 'وثيقة سنوية شاملة',
      },
    ],
    trips: [
      {
        tripNo: 'TR-2024-001',
        destination: 'القاهرة → الكويت',
        departure: '2024-01-15',
        driver: 'يوسف الحناوي',
        status: 'وصلت',
      },
      {
        tripNo: 'TR-2024-005',
        destination: 'الإسكندرية → الكويت',
        departure: '2024-01-05',
        driver: 'يوسف الحناوي',
        status: 'مغلقة',
      },
    ],
    timeline: [
      {
        date: '2026-05-28',
        kind: 'maintenance',
        icon: '🛢',
        title: 'تغيير زيت · مركز خدمة مرسيدس',
        subtitle: '1,450 ج.م · زيت + فلتر',
      },
      {
        date: '2025-08-01',
        kind: 'insurance',
        icon: '🛡',
        title: 'تأمين · شركة مصر للتأمين',
        subtitle: '18,500 ج.م · وثيقة شاملة سنوية',
      },
      {
        date: '2024-01-15',
        kind: 'trip',
        icon: '🚛',
        title: 'TR-2024-001 — القاهرة → الكويت',
        subtitle: 'يوسف الحناوي · وصلت',
      },
      {
        date: '2024-01-05',
        kind: 'trip',
        icon: '🚛',
        title: 'TR-2024-005 — الإسكندرية → الكويت',
        subtitle: 'يوسف الحناوي · مغلقة',
      },
    ],
  },
  {
    id: 2,
    plateNumber: 'ص ع د ٥٦٧٨',
    vehicleType: 'فولفو FH16',
    vehicleModel: '2021',
    vehicleColor: 'أزرق',
    capacityKg: 24000,
    transportType: 'owned',
    vehicleLicenseNo: 'LIC-002',
    driverName: 'حسن المغربي',
    licenseExpiry: '2026-10-30',
    insurance: { count: 1, nearestExpiry: '2026-07-20', state: 'expiringSoon' },
    maintenanceCostEgp: 10400,
    status: 'onRoad',
    ownerName: 'مؤسسة الرماح',
    ownerPhone: '+966501234567',
    ownerAddress: 'الرياض، المملكة العربية السعودية',
    stats: {
      currentDriver: 'حسن المغربي',
      currentTrip: 'TR-2024-002',
      totalTrips: 1,
      tripsThisMonth: 0,
      distanceKm: '—',
      revenue: '≈ 175,006 ج.م',
      expenses: '≈ 5,205 ج.م',
      maintenanceCost: '≈ 10,400 ج.م',
      fuelCost: '—',
      fines: 0,
      thisMonthCost: '≈ 0 ج.م',
      thisYearCost: '≈ 10,400 ج.م',
      currentMileageKm: '210,500 كم',
      openReminders: 0,
      renewalCount: 2,
      renewalBannerText:
        'انتهاء تأمين الشاحنة ص ع د ٥٦٧٨ — التعاونية (السعودية) · خلال 4 يوم متبقٍ · فحص دوري — ص ع د ٥٦٧٨ · خلال 4 يوم متبقٍ',
      renewalBannerTextEn:
        '🛡 Truck insurance expiry ص ع د ٥٦٧٨ — التعاونية — السعودية (السعودية) · in 4 days left · Periodic Inspection — ص ع د ٥٦٧٨ · in 4 days left',
      currentTripNo: 'TR-2024-002',
      currentTripShipments: 4,
    },
    vehicleRecords: [
      {
        id: 201,
        date: '2026-04-15',
        recordType: 'tires',
        recordTypeLabel: '🛞 إطارات',
        mileageKm: 210500,
        costEgp: 9600,
        costDisplay: '9,600 ج.م',
        supplier: 'مؤسسة الإطارات الدولية',
        invoiceNo: 'MNT-1090',
        nextServiceDate: '2027-04-15',
        status: 'done',
        notes: '4 إطارات خلفية',
      },
      {
        id: 202,
        date: '2026-01-20',
        recordType: 'inspection',
        recordTypeLabel: '🔍 فحص دوري',
        mileageKm: 205000,
        costEgp: 800,
        costDisplay: '800 ج.م',
        supplier: 'مركز الفحص الفني',
        invoiceNo: 'CHK-3321',
        nextServiceDate: '2026-07-20',
        status: 'done',
        notes: 'فحص دوري نصف سنوي',
      },
    ],
    insuranceRecords: [
      {
        id: 301,
        insuranceCompany: 'التعاونية — السعودية',
        country: 'السعودية',
        policyNo: 'SA-55102',
        coverageType: 'عبور دولي',
        issueDate: '2025-09-15',
        expiryDate: '2026-07-20',
        costDisplay: '2,900 ر.س',
        state: 'expiringSoon',
        attachment: '',
        notes: '—',
      },
    ],
    trips: [
      {
        tripNo: 'TR-2024-002',
        destination: 'الإسكندرية → السعودية',
        departure: '2024-01-16',
        driver: 'حسن المغربي',
        status: 'وصلت',
      },
    ],
    timeline: [
      {
        date: '2026-04-15',
        kind: 'maintenance',
        icon: '🛞',
        title: 'إطارات · مؤسسة الإطارات الدولية',
        subtitle: '9,600 ج.م · 4 إطارات خلفية',
      },
      {
        date: '2026-01-20',
        kind: 'maintenance',
        icon: '🔍',
        title: 'فحص دوري · مركز الفحص الفني',
        subtitle: '800 ج.م · فحص دوري نصف سنوي',
      },
      {
        date: '2024-01-16',
        kind: 'trip',
        icon: '🚛',
        title: 'TR-2024-002 — الإسكندرية → السعودية',
        subtitle: 'حسن المغربي · وصلت',
      },
    ],
  },
];

export const TRUCK_FIXTURES: readonly Truck[] = [...TRUCK_FIXTURES_BASE, ...TRUCK_FIXTURES_EXTRA];
