import { Truck } from './models/truck.model';

// ── Trucks 3 & 4 ─────────────────────────────────────────────────────────────
// Split from trucks.data.ts to stay within the 400-line limit (Charter §2).
export const TRUCK_FIXTURES_EXTRA: readonly Truck[] = [
  {
    id: 3,
    plateNumber: 'ل م ن ٩٠١٢',
    vehicleType: 'مان TGX',
    vehicleModel: '2023',
    vehicleColor: 'أحمر',
    capacityKg: 22000,
    transportType: 'rented',
    vehicleLicenseNo: 'LIC-003',
    driverName: null,
    licenseExpiry: '2027-08-19',
    insurance: null,
    maintenanceCostEgp: 6000,
    status: 'available',
    ownerName: 'شركة النقل السريع',
    ownerPhone: '+966509876543',
    ownerAddress: 'جدة، المملكة العربية السعودية',
    stats: {
      currentDriver: '—',
      currentTrip: 'TR-2024-004',
      totalTrips: 2,
      tripsThisMonth: 0,
      distanceKm: '—',
      revenue: '≈ 134,996 ج.م',
      expenses: '≈ 0 ج.م',
      maintenanceCost: '≈ 6,000 ج.م',
      fuelCost: '—',
      fines: 0,
      thisMonthCost: '≈ 2,800 ج.م',
      thisYearCost: '≈ 6,000 ج.م',
      currentMileageKm: '98,000 كم',
      openReminders: 1,
      renewalCount: 1,
      renewalBannerText: 'بطارية — ل م ن ٩٠١٢ · خلال 4 يوم متبقٍ',
      renewalBannerTextEn: 'Battery — ل م ن ٩٠١٢ · in 4 days left',
      currentTripNo: 'TR-2024-004',
      currentTripShipments: 3,
    },
    vehicleRecords: [
      {
        id: 301,
        date: '2026-07-20',
        recordType: 'battery',
        recordTypeLabel: '🔋 بطارية',
        mileageKm: null,
        costEgp: 2800,
        costDisplay: '2,800 ج.م',
        supplier: 'مؤسسة البطاريات',
        invoiceNo: '—',
        nextServiceDate: '2026-07-20',
        status: 'scheduled',
        notes: 'استبدال بطارية مجدول',
      },
      {
        id: 302,
        date: '2026-06-10',
        recordType: 'brakeService',
        recordTypeLabel: '🛑 فرامل',
        mileageKm: 98000,
        costEgp: 3200,
        costDisplay: '3,200 ج.م',
        supplier: 'ورشة النقل السريع',
        invoiceNo: 'MNT-1122',
        nextServiceDate: null,
        status: 'done',
        notes: 'تيل فرامل أمامي',
      },
    ],
    insuranceRecords: [],
    trips: [
      {
        tripNo: 'TR-2024-004',
        destination: 'القاهرة → قطر',
        departure: '2024-01-22',
        driver: 'عبدالله رشاد',
        status: 'مخطط',
      },
      {
        tripNo: 'TR-2024-006',
        destination: 'القاهرة → البحرين',
        departure: '2024-01-22',
        driver: 'إبراهيم سعيد',
        status: 'مخطط',
      },
    ],
    timeline: [
      {
        date: '2026-07-20',
        kind: 'maintenance',
        icon: '🔋',
        title: 'بطارية · مؤسسة البطاريات',
        subtitle: '2,800 ج.م · استبدال بطارية مجدول',
      },
      {
        date: '2026-06-10',
        kind: 'maintenance',
        icon: '🛑',
        title: 'فرامل · ورشة النقل السريع',
        subtitle: '3,200 ج.م · تيل فرامل أمامي',
      },
      {
        date: '2024-01-22',
        kind: 'trip',
        icon: '🚛',
        title: 'TR-2024-004 — القاهرة → قطر',
        subtitle: 'عبدالله رشاد · مخطط',
      },
      {
        date: '2024-01-22',
        kind: 'trip',
        icon: '🚛',
        title: 'TR-2024-006 — القاهرة → البحرين',
        subtitle: 'إبراهيم سعيد · مخطط',
      },
    ],
  },
  {
    id: 4,
    plateNumber: 'ر س ط ٣٤٥٦',
    vehicleType: 'سكانيا R500',
    vehicleModel: '2020',
    vehicleColor: 'رمادي',
    capacityKg: 18000,
    transportType: 'owned',
    vehicleLicenseNo: 'LIC-004',
    driverName: 'طارق سليمان',
    licenseExpiry: '2026-12-05',
    insurance: { count: 1, nearestExpiry: '2026-06-15', state: 'expired' },
    maintenanceCostEgp: 6900,
    status: 'onRoad',
    ownerName: 'مؤسسة الرماح',
    ownerPhone: '+966501234567',
    ownerAddress: 'الرياض، المملكة العربية السعودية',
    stats: {
      currentDriver: 'طارق سليمان',
      currentTrip: null,
      totalTrips: 1,
      tripsThisMonth: 0,
      distanceKm: '3,400 كم',
      revenue: '≈ 124,000 ج.م',
      expenses: '≈ 2,960 ج.م',
      maintenanceCost: '≈ 6,900 ج.م',
      fuelCost: '—',
      fines: 0,
      thisMonthCost: '≈ 0 ج.م',
      thisYearCost: '≈ 6,900 ج.م',
      currentMileageKm: '245,300 كم',
      openReminders: 0,
      renewalCount: 2,
      renewalBannerText:
        'انتهاء تأمين الشاحنة ر س ط ٣٤٥٦ — أليانز الدولية (دولي) · منتهية منذ 15 يوم · تغيير زيت — ر س ط ٣٤٥٦ · منتهية منذ 4 يوم',
      renewalBannerTextEn:
        '🛡 Truck insurance expiry ر س ط ٣٤٥٦ — أليانز الدولية (دولي) · expired since 15 days · Oil Change — ر س ط ٣٤٥٦ · expired since 4 days',
      currentTripNo: null,
      currentTripShipments: null,
    },
    vehicleRecords: [
      {
        id: 401,
        date: '2026-06-22',
        recordType: 'repair',
        recordTypeLabel: '🛠 إصلاح',
        mileageKm: 245300,
        costEgp: 5400,
        costDisplay: '5,400 ج.م',
        supplier: 'ورشة الأمانة',
        invoiceNo: 'MNT-1130',
        nextServiceDate: null,
        status: 'done',
        notes: 'إصلاح مضخة الوقود بعد عطل مفاجئ',
      },
      {
        id: 402,
        date: '2026-03-30',
        recordType: 'oilChange',
        recordTypeLabel: '🛢 تغيير زيت',
        mileageKm: 238000,
        costEgp: 1500,
        costDisplay: '1,500 ج.م',
        supplier: 'مركز خدمة سكانيا',
        invoiceNo: 'MNT-1075',
        nextServiceDate: '2026-07-12',
        status: 'done',
        notes: '—',
      },
    ],
    insuranceRecords: [
      {
        id: 401,
        insuranceCompany: 'أليانز الدولية',
        country: 'دولي',
        policyNo: 'INT-99001',
        coverageType: 'شحن دولي شامل',
        issueDate: '2024-07-01',
        expiryDate: '2026-07-01',
        costDisplay: '1,200 $',
        state: 'expired',
        attachment: '',
        notes: 'بحاجة إلى تجديد',
      },
    ],
    trips: [
      {
        tripNo: 'TR-2024-003',
        destination: 'القاهرة → الإمارات',
        departure: '2024-01-10',
        driver: 'طارق سليمان',
        status: 'مكتملة',
      },
    ],
    timeline: [
      {
        date: '2026-06-22',
        kind: 'maintenance',
        icon: '🛠',
        title: 'إصلاح · ورشة الأمانة',
        subtitle: '5,400 ج.م · إصلاح مضخة الوقود بعد عطل مفاجئ',
      },
      {
        date: '2026-03-30',
        kind: 'maintenance',
        icon: '🛢',
        title: 'تغيير زيت · مركز خدمة سكانيا',
        subtitle: '1,500 ج.م · —',
      },
      {
        date: '2024-01-10',
        kind: 'trip',
        icon: '🚛',
        title: 'TR-2024-003 — القاهرة → الإمارات',
        subtitle: 'طارق سليمان · مكتملة',
      },
    ],
  },
];
