import { Shipment } from './models/shipment.model';

/**
 * UI fixtures transcribed from the Shipping Prototype shipments list
 * (screenshots of the live prototype, 2026-07-19 — 25 shipments across 4 pages).
 * Financial values are display data only until the backend owns calculations.
 *
 * `remainingBalance`, `tripNumber` and `collectionStatus` are `null` for shipments
 * that have not been dispatched yet (`ready` / `draft`) — the prototype shows a
 * '—' placeholder for those columns until the shipment is assigned to a trip.
 */
export const SHIPMENT_FIXTURES: readonly Shipment[] = [
  {
    id: 1,
    customerName: 'أحمد عبد الله',
    destinationCountry: 'الكويت',
    destinationCity: 'الكويت',
    warehouse: 'cairo',
    packageCount: 10,
    finalValue: 196,
    remainingBalance: 137,
    currency: 'KWD',
    tripNumber: 'TR-2024-001',
    collectionStatus: 'partialCollected',
    status: 'inTransit',
    hasShortage: false,
  },
  {
    id: 2,
    customerName: 'شركة النيل للاستيراد والتصدير',
    destinationCountry: 'الكويت',
    destinationCity: 'حولي',
    warehouse: 'cairo',
    packageCount: 25,
    finalValue: 356,
    remainingBalance: 249,
    currency: 'KWD',
    tripNumber: 'TR-2024-001',
    collectionStatus: 'partialCollected',
    status: 'inTransit',
    hasShortage: false,
  },
  {
    id: 3,
    customerName: 'محمود السيد',
    destinationCountry: 'الكويت',
    destinationCity: 'الجهراء',
    warehouse: 'cairo',
    packageCount: 8,
    finalValue: 129,
    remainingBalance: 90,
    currency: 'KWD',
    tripNumber: 'TR-2024-001',
    collectionStatus: 'partialCollected',
    status: 'inTransit',
    hasShortage: false,
  },
  {
    id: 4,
    customerName: 'مؤسسة الدلتا التجارية',
    destinationCountry: 'السعودية',
    destinationCity: 'الرياض',
    warehouse: 'alexandria',
    packageCount: 15,
    finalValue: 3462,
    remainingBalance: 2423,
    currency: 'SAR',
    tripNumber: 'TR-2024-002',
    collectionStatus: 'partialCollected',
    status: 'inTransit',
    hasShortage: false,
  },
  {
    id: 5,
    customerName: 'فاطمة إبراهيم',
    destinationCountry: 'السعودية',
    destinationCity: 'جدة',
    warehouse: 'alexandria',
    packageCount: 5,
    finalValue: 923,
    remainingBalance: 646,
    currency: 'SAR',
    tripNumber: 'TR-2024-002',
    collectionStatus: 'partialCollected',
    status: 'inTransit',
    hasShortage: false,
  },
  {
    id: 6,
    customerName: 'شركة المستقبل للتجارة',
    destinationCountry: 'السعودية',
    destinationCity: 'الدمام',
    warehouse: 'alexandria',
    packageCount: 30,
    finalValue: 6308,
    remainingBalance: 4416,
    currency: 'SAR',
    tripNumber: 'TR-2024-002',
    collectionStatus: 'partialCollected',
    status: 'inTransit',
    hasShortage: false,
  },
  {
    id: 7,
    customerName: 'خالد عبد الرحمن',
    destinationCountry: 'السعودية',
    destinationCity: 'مكة',
    warehouse: 'alexandria',
    packageCount: 12,
    finalValue: 2769,
    remainingBalance: 1938,
    currency: 'SAR',
    tripNumber: 'TR-2024-002',
    collectionStatus: 'partialCollected',
    status: 'inTransit',
    hasShortage: false,
  },
  {
    id: 8,
    customerName: 'مجموعة النصر',
    destinationCountry: 'الإمارات',
    destinationCity: 'دبي',
    warehouse: 'cairo',
    packageCount: 20,
    finalValue: 960,
    remainingBalance: 480,
    currency: 'USD',
    tripNumber: 'TR-2024-003',
    collectionStatus: 'partialCollected',
    status: 'delivered',
    hasShortage: true,
  },
  {
    id: 9,
    customerName: 'سارة منصور',
    destinationCountry: 'الإمارات',
    destinationCity: 'أبوظبي',
    warehouse: 'cairo',
    packageCount: 18,
    finalValue: 1040,
    remainingBalance: 520,
    currency: 'USD',
    tripNumber: 'TR-2024-003',
    collectionStatus: 'partialCollected',
    status: 'delivered',
    hasShortage: false,
  },
  {
    id: 10,
    customerName: 'عمر الشناوي',
    destinationCountry: 'الإمارات',
    destinationCity: 'الشارقة',
    warehouse: 'cairo',
    packageCount: 7,
    finalValue: 480,
    remainingBalance: 240,
    currency: 'USD',
    tripNumber: 'TR-2024-003',
    collectionStatus: 'partialCollected',
    status: 'delivered',
    hasShortage: false,
  },
  {
    id: 11,
    customerName: 'شركة الأهرام للإلكترونيات',
    destinationCountry: 'قطر',
    destinationCity: 'الدوحة',
    warehouse: 'cairo',
    packageCount: 14,
    finalValue: 1220,
    remainingBalance: 1220,
    currency: 'USD',
    tripNumber: 'TR-2024-004',
    collectionStatus: 'uncollected',
    status: 'assigned',
    hasShortage: false,
  },
  {
    id: 12,
    customerName: 'ناصر حسن',
    destinationCountry: 'قطر',
    destinationCity: 'الريان',
    warehouse: 'cairo',
    packageCount: 9,
    finalValue: 780,
    remainingBalance: 780,
    currency: 'USD',
    tripNumber: 'TR-2024-004',
    collectionStatus: 'uncollected',
    status: 'assigned',
    hasShortage: false,
  },
  {
    id: 13,
    customerName: 'مؤسسة الربيع',
    destinationCountry: 'الكويت',
    destinationCity: 'الكويت',
    warehouse: 'alexandria',
    packageCount: 22,
    finalValue: 448,
    remainingBalance: 0,
    currency: 'KWD',
    tripNumber: 'TR-2024-005',
    collectionStatus: 'collected',
    status: 'closed',
    hasShortage: true,
  },
  {
    id: 14,
    customerName: 'علي الدسوقي',
    destinationCountry: 'الكويت',
    destinationCity: 'الجهراء',
    warehouse: 'alexandria',
    packageCount: 11,
    finalValue: 190,
    remainingBalance: 0,
    currency: 'KWD',
    tripNumber: 'TR-2024-005',
    collectionStatus: 'collected',
    status: 'closed',
    hasShortage: false,
  },
  {
    id: 15,
    customerName: 'شركة الفجر للملابس الجاهزة',
    destinationCountry: 'الكويت',
    destinationCity: 'حولي',
    warehouse: 'alexandria',
    packageCount: 16,
    finalValue: 258,
    remainingBalance: 0,
    currency: 'KWD',
    tripNumber: 'TR-2024-005',
    collectionStatus: 'collected',
    status: 'closed',
    hasShortage: false,
  },
  {
    id: 16,
    customerName: 'أحمد عبد الله',
    destinationCountry: 'البحرين',
    destinationCity: 'المنامة',
    warehouse: 'cairo',
    packageCount: 6,
    finalValue: 560,
    remainingBalance: 560,
    currency: 'USD',
    tripNumber: 'TR-2024-006',
    collectionStatus: 'uncollected',
    status: 'assigned',
    hasShortage: false,
  },
  {
    id: 17,
    customerName: 'شركة النيل للاستيراد والتصدير',
    destinationCountry: 'البحرين',
    destinationCity: 'المحرق',
    warehouse: 'cairo',
    packageCount: 19,
    finalValue: 920,
    remainingBalance: 920,
    currency: 'USD',
    tripNumber: 'TR-2024-006',
    collectionStatus: 'uncollected',
    status: 'assigned',
    hasShortage: false,
  },
  {
    id: 18,
    customerName: 'سمير عبد الله',
    destinationCountry: 'مصر',
    destinationCity: 'الإسكندرية',
    warehouse: 'cairo',
    packageCount: 3,
    finalValue: 9000,
    remainingBalance: null,
    currency: 'EGP',
    tripNumber: null,
    collectionStatus: null,
    status: 'ready',
    hasShortage: false,
  },
  {
    id: 19,
    customerName: 'مؤسسة الدلتا التجارية',
    destinationCountry: 'السعودية',
    destinationCity: 'جدة',
    warehouse: 'alexandria',
    packageCount: 13,
    finalValue: 2692,
    remainingBalance: null,
    currency: 'SAR',
    tripNumber: null,
    collectionStatus: null,
    status: 'ready',
    hasShortage: false,
  },
  {
    id: 20,
    customerName: 'فاطمة إبراهيم',
    destinationCountry: 'الإمارات',
    destinationCity: 'دبي',
    warehouse: 'cairo',
    packageCount: 27,
    finalValue: 1360,
    remainingBalance: null,
    currency: 'USD',
    tripNumber: null,
    collectionStatus: null,
    status: 'ready',
    hasShortage: false,
  },
  {
    id: 21,
    customerName: 'شركة المستقبل للتجارة',
    destinationCountry: 'الكويت',
    destinationCity: 'الكويت',
    warehouse: 'cairo',
    packageCount: 4,
    finalValue: 110,
    remainingBalance: null,
    currency: 'KWD',
    tripNumber: null,
    collectionStatus: null,
    status: 'draft',
    hasShortage: false,
  },
  {
    id: 22,
    customerName: 'خالد عبد الرحمن',
    destinationCountry: 'قطر',
    destinationCity: 'الدوحة',
    warehouse: 'cairo',
    packageCount: 8,
    finalValue: 580,
    remainingBalance: null,
    currency: 'USD',
    tripNumber: null,
    collectionStatus: null,
    status: 'draft',
    hasShortage: false,
  },
  {
    id: 23,
    customerName: 'مجموعة النصر',
    destinationCountry: 'السعودية',
    destinationCity: 'الرياض',
    warehouse: 'alexandria',
    packageCount: 11,
    finalValue: 2538,
    remainingBalance: null,
    currency: 'SAR',
    tripNumber: null,
    collectionStatus: null,
    status: 'ready',
    hasShortage: false,
  },
  {
    id: 24,
    customerName: 'وليد كرم',
    destinationCountry: 'الإمارات',
    destinationCity: 'دبي',
    warehouse: 'cairo',
    packageCount: 6,
    finalValue: 520,
    remainingBalance: null,
    currency: 'USD',
    tripNumber: null,
    collectionStatus: null,
    status: 'draft',
    hasShortage: false,
  },
  {
    id: 25,
    customerName: 'عمر الشناوي',
    destinationCountry: 'الكويت',
    destinationCity: 'الكويت',
    warehouse: 'alexandria',
    packageCount: 17,
    finalValue: 252,
    remainingBalance: null,
    currency: 'KWD',
    tripNumber: null,
    collectionStatus: null,
    status: 'ready',
    hasShortage: false,
  },
];
