/* eslint-disable max-lines */
import { ShipmentDetails } from './models/shipment-details.model';

/**
 * UI fixtures transcribed from the Shipping Prototype shipment-details modal
 * (screenshots of the live prototype, 2026-07-19 — all 25 shipments).
 * Financial values, document numbers and timestamps are display data only
 * until the backend owns this screen.
 */
export const SHIPMENT_DETAILS_FIXTURES: readonly ShipmentDetails[] = [
  {
    id: 1,
    status: 'inTransit',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-001' },
      { key: 'shipment', state: 'done', reference: 'SH-001' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-001' },
      { key: 'delivery', state: 'current', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'أحمد عبد الله',
      senderPhone: '+201001112223',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'تاجر تجزئة',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'الكويت',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'other',
      tripNumber: 'TR-2024-001',
      driverName: 'يوسف الحناوي',
      currentLocationApprox: 'الطريق الصحراوي - القاهرة السويس (تقريبي)',
    },
    packageLines: [
      {
        itemName: 'أدوات منزلية',
        packageCount: 10,
        pieceCount: 100,
        netWeightKg: 192,
        grossWeightKg: 200,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 196,
      discounts: null,
      finalValue: 196,
      paid: 59,
      remaining: 137,
      collectedByDriver: 0,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 59, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-001-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 59,
          currency: 'KWD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }, { kind: 'paymentReceipt' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00001' },
      { kind: 'waybill', referenceNo: 'WB-001' },
      { kind: 'trip', referenceNo: 'TR-2024-001' },
      { kind: 'truck', referenceNo: 'ق ن ز ١١٣٤' },
      { kind: 'driver', referenceNo: 'يوسف الحناوي' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'PR-001' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 2,
    status: 'inTransit',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-002' },
      { key: 'shipment', state: 'done', reference: 'SH-002' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-001' },
      { key: 'delivery', state: 'current', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'شركة النيل للاستيراد والتصدير',
      senderPhone: '+201002223334',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'تاجر جملة',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'حولي',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'clothing',
      tripNumber: 'TR-2024-001',
      driverName: 'يوسف الحناوي',
      currentLocationApprox: 'الطريق الصحراوي - القاهرة السويس (تقريبي)',
    },
    packageLines: [
      {
        itemName: 'ملابس جاهزة',
        packageCount: 25,
        pieceCount: 250,
        netWeightKg: 480,
        grossWeightKg: 500,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 356,
      discounts: null,
      finalValue: 356,
      paid: 107,
      remaining: 249,
      collectedByDriver: 0,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 107, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-002-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 107,
          currency: 'KWD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }, { kind: 'paymentReceipt' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00002' },
      { kind: 'waybill', referenceNo: 'WB-002' },
      { kind: 'trip', referenceNo: 'TR-2024-001' },
      { kind: 'truck', referenceNo: 'ق ن ز ١١٣٤' },
      { kind: 'driver', referenceNo: 'يوسف الحناوي' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'PR-002' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 3,
    status: 'inTransit',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-003' },
      { key: 'shipment', state: 'done', reference: 'SH-003' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-001' },
      { key: 'delivery', state: 'current', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'محمود السيد',
      senderPhone: '+201223456789',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'تاجر جملة',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'الجهراء',
      direction: 'inbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'furniture',
      tripNumber: 'TR-2024-001',
      driverName: 'يوسف الحناوي',
      currentLocationApprox: 'الطريق الصحراوي - القاهرة السويس (تقريبي)',
    },
    packageLines: [
      {
        itemName: 'أدوات منزلية بلاستيكية',
        packageCount: 8,
        pieceCount: 80,
        netWeightKg: 307,
        grossWeightKg: 320,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 129,
      discounts: null,
      finalValue: 129,
      paid: 39,
      remaining: 90,
      collectedByDriver: 0,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 39, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-003-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 39,
          currency: 'KWD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }, { kind: 'paymentReceipt' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00003' },
      { kind: 'waybill', referenceNo: 'WB-003' },
      { kind: 'trip', referenceNo: 'TR-2024-001' },
      { kind: 'truck', referenceNo: 'ق ن ز ١١٣٤' },
      { kind: 'driver', referenceNo: 'يوسف الحناوي' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'PR-003' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 4,
    status: 'inTransit',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-004' },
      { key: 'shipment', state: 'done', reference: 'SH-004' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-002' },
      { key: 'delivery', state: 'current', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'مؤسسة الدلتا التجارية',
      senderPhone: '+201004567890',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'مجمع الرياض التجاري',
      receiverPhone: null,
      destinationCountry: 'السعودية',
      destinationCity: 'الرياض',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'industrialEquipment',
      tripNumber: 'TR-2024-002',
      driverName: 'حسن المغربي',
      currentLocationApprox: 'معبر نويبع البحري (تقريبي)',
    },
    packageLines: [
      {
        itemName: 'مفروشات منزلية',
        packageCount: 15,
        pieceCount: 150,
        netWeightKg: 768,
        grossWeightKg: 800,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'SAR',
      priceBeforeDiscount: 3462,
      discounts: null,
      finalValue: 3462,
      paid: 1039,
      remaining: 2423,
      collectedByDriver: 0,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 1039, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-004-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 1039,
          currency: 'SAR',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }, { kind: 'paymentReceipt' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00004' },
      { kind: 'waybill', referenceNo: 'WB-004' },
      { kind: 'trip', referenceNo: 'TR-2024-002' },
      { kind: 'truck', referenceNo: 'س ع ط ٤٥٦٧' },
      { kind: 'driver', referenceNo: 'حسن المغربي' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'PR-004' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 5,
    status: 'inTransit',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-005' },
      { key: 'shipment', state: 'done', reference: 'SH-005' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-002' },
      { key: 'delivery', state: 'current', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'فاطمة إبراهيم',
      senderPhone: '+201115678901',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'متجر جدة',
      receiverPhone: null,
      destinationCountry: 'السعودية',
      destinationCity: 'جدة',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'buildingMaterials',
      tripNumber: 'TR-2024-002',
      driverName: 'حسن المغربي',
      currentLocationApprox: 'معبر نويبع البحري (تقريبي)',
    },
    packageLines: [
      {
        itemName: 'سجاد صلاة',
        packageCount: 5,
        pieceCount: 50,
        netWeightKg: 192,
        grossWeightKg: 200,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'SAR',
      priceBeforeDiscount: 923,
      discounts: null,
      finalValue: 923,
      paid: 277,
      remaining: 646,
      collectedByDriver: 0,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 277, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-005-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 277,
          currency: 'SAR',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }, { kind: 'paymentReceipt' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00005' },
      { kind: 'waybill', referenceNo: 'WB-005' },
      { kind: 'trip', referenceNo: 'TR-2024-002' },
      { kind: 'truck', referenceNo: 'س ع ط ٤٥٦٧' },
      { kind: 'driver', referenceNo: 'حسن المغربي' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'PR-005' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 6,
    status: 'inTransit',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-006' },
      { key: 'shipment', state: 'done', reference: 'SH-006' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-002' },
      { key: 'delivery', state: 'current', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'شركة المستقبل للتجارة',
      senderPhone: '+201226789012',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'شركة استيراد',
      receiverPhone: null,
      destinationCountry: 'السعودية',
      destinationCity: 'الدمام',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'clothing',
      tripNumber: 'TR-2024-002',
      driverName: 'حسن المغربي',
      currentLocationApprox: 'المياه الإقليمية (تقريبي)',
    },
    packageLines: [
      {
        itemName: 'أثاث منزلي',
        packageCount: 30,
        pieceCount: 300,
        netWeightKg: 1440,
        grossWeightKg: 1500,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'SAR',
      priceBeforeDiscount: 6308,
      discounts: null,
      finalValue: 6308,
      paid: 1892,
      remaining: 4416,
      collectedByDriver: 0,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 1892, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-006-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 1892,
          currency: 'SAR',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }, { kind: 'paymentReceipt' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00006' },
      { kind: 'waybill', referenceNo: 'WB-006' },
      { kind: 'trip', referenceNo: 'TR-2024-002' },
      { kind: 'truck', referenceNo: 'س ع ط ٤٥٦٧' },
      { kind: 'driver', referenceNo: 'حسن المغربي' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'PR-006' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 7,
    status: 'inTransit',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-007' },
      { key: 'shipment', state: 'done', reference: 'SH-007' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-002' },
      { key: 'delivery', state: 'current', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'خالد عبد الرحمن',
      senderPhone: '+201007890123',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'متجر مكة',
      receiverPhone: null,
      destinationCountry: 'السعودية',
      destinationCity: 'مكة',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'electronics',
      tripNumber: 'TR-2024-002',
      driverName: 'حسن المغربي',
      currentLocationApprox: 'المياه الإقليمية (تقريبي)',
    },
    packageLines: [
      {
        itemName: 'إكسسوارات سيارات',
        packageCount: 12,
        pieceCount: 120,
        netWeightKg: 576,
        grossWeightKg: 600,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'SAR',
      priceBeforeDiscount: 2769,
      discounts: null,
      finalValue: 2769,
      paid: 831,
      remaining: 1938,
      collectedByDriver: 0,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 831, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-007-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 831,
          currency: 'SAR',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }, { kind: 'paymentReceipt' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00007' },
      { kind: 'waybill', referenceNo: 'WB-007' },
      { kind: 'trip', referenceNo: 'TR-2024-002' },
      { kind: 'truck', referenceNo: 'س ع ط ٤٥٦٧' },
      { kind: 'driver', referenceNo: 'حسن المغربي' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'PR-007' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 8,
    status: 'delivered',
    hasShortage: true,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-008' },
      { key: 'shipment', state: 'done', reference: 'SH-008' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-003' },
      { key: 'delivery', state: 'done', reference: 'العجز' },
      { key: 'settlement', state: 'current', reference: null },
    ],
    summary: {
      senderName: 'مجموعة النصر',
      senderPhone: '+201118901234',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'محل دبي',
      receiverPhone: null,
      destinationCountry: 'الإمارات',
      destinationCity: 'دبي',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'foodstuff',
      tripNumber: 'TR-2024-003',
      driverName: 'طارق سليمان',
      currentLocationApprox: 'دبي',
    },
    packageLines: [
      {
        itemName: 'أدوات بلاستيكية',
        packageCount: 20,
        pieceCount: 200,
        netWeightKg: 912,
        grossWeightKg: 950,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 40,
        shortageCount: 160,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 960,
      discounts: null,
      finalValue: 960,
      paid: 480,
      remaining: 480,
      collectedByDriver: 288,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 480, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-008-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 480,
          currency: 'USD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: '2024-01-18 14:00', done: true },
      { label: 'تم التحقق', time: '2024-01-18 18:00', done: true },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم التحقق من التسليم', actor: 'محمود عبد الحليم', time: '2026-07-13 12:09' },
      { message: 'تم التسليم بعجز 160 قطعة', actor: 'السائق', time: '2026-07-13 12:09' },
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [
      { kind: 'receivingReceipt' },
      { kind: 'packingList' },
      { kind: 'deliveryAcknowledgment' },
      { kind: 'paymentReceipt' },
    ],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00008' },
      { kind: 'waybill', referenceNo: 'WB-008' },
      { kind: 'trip', referenceNo: 'TR-2024-003' },
      { kind: 'truck', referenceNo: 'ر س ط ٣٤٥٦' },
      { kind: 'driver', referenceNo: 'طارق سليمان' },
      { kind: 'deliveryReceipt', referenceNo: 'DR-008' },
      { kind: 'invoice', referenceNo: 'INV-2024-001' },
      { kind: 'paymentReceipt', referenceNo: 'PR-008' },
      { kind: 'settlement', referenceNo: 'SET-2024-001' },
    ],
  },
  {
    id: 9,
    status: 'delivered',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-009' },
      { key: 'shipment', state: 'done', reference: 'SH-009' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-003' },
      { key: 'delivery', state: 'done', reference: 'مُسلَّمة' },
      { key: 'settlement', state: 'current', reference: null },
    ],
    summary: {
      senderName: 'سارة منصور',
      senderPhone: '+201229012345',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'مكتب استيراد',
      receiverPhone: null,
      destinationCountry: 'الإمارات',
      destinationCity: 'أبوظبي',
      direction: 'inbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'furniture',
      tripNumber: 'TR-2024-003',
      driverName: 'طارق سليمان',
      currentLocationApprox: 'أبوظبي',
    },
    packageLines: [
      {
        itemName: 'أجهزة كهربائية',
        packageCount: 18,
        pieceCount: 180,
        netWeightKg: 816,
        grossWeightKg: 850,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 180,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 1040,
      discounts: null,
      finalValue: 1040,
      paid: 520,
      remaining: 520,
      collectedByDriver: 312,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 520, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-009-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 520,
          currency: 'USD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: '2024-01-18 14:00', done: true },
      { label: 'تم التحقق', time: '2024-01-18 18:00', done: true },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم التسليم', actor: 'السائق', time: '2026-07-13 12:09' },
      { message: 'تم التحقق من التسليم', actor: 'محمود عبد الحليم', time: '2026-07-13 12:09' },
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [
      { kind: 'receivingReceipt' },
      { kind: 'packingList' },
      { kind: 'deliveryAcknowledgment' },
      { kind: 'paymentReceipt' },
    ],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00009' },
      { kind: 'waybill', referenceNo: 'WB-009' },
      { kind: 'trip', referenceNo: 'TR-2024-003' },
      { kind: 'truck', referenceNo: 'ر س ط ٣٤٥٦' },
      { kind: 'driver', referenceNo: 'طارق سليمان' },
      { kind: 'deliveryReceipt', referenceNo: 'DR-009' },
      { kind: 'invoice', referenceNo: 'INV-2024-002' },
      { kind: 'paymentReceipt', referenceNo: 'PR-009' },
      { kind: 'settlement', referenceNo: 'SET-2024-001' },
    ],
  },
  {
    id: 10,
    status: 'delivered',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-010' },
      { key: 'shipment', state: 'done', reference: 'SH-010' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-003' },
      { key: 'delivery', state: 'done', reference: 'مُسلَّمة' },
      { key: 'settlement', state: 'current', reference: null },
    ],
    summary: {
      senderName: 'عمر الشناوي',
      senderPhone: '+201001122334',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'تاجر الشارقة',
      receiverPhone: null,
      destinationCountry: 'الإمارات',
      destinationCity: 'الشارقة',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'industrialEquipment',
      tripNumber: 'TR-2024-003',
      driverName: 'طارق سليمان',
      currentLocationApprox: 'الشارقة',
    },
    packageLines: [
      {
        itemName: 'ملابس أطفال',
        packageCount: 7,
        pieceCount: 70,
        netWeightKg: 269,
        grossWeightKg: 280,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 70,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 480,
      discounts: null,
      finalValue: 480,
      paid: 240,
      remaining: 240,
      collectedByDriver: 144,
      collectionStatus: 'partialCollected',
      collectedByCurrency: [{ amount: 240, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-010-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 240,
          currency: 'USD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: '2024-01-18 14:00', done: true },
      { label: 'تم التحقق', time: '2024-01-18 18:00', done: true },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم التسليم', actor: 'السائق', time: '2026-07-13 12:09' },
      { message: 'تم التحقق من التسليم', actor: 'محمود عبد الحليم', time: '2026-07-13 12:09' },
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [
      { kind: 'receivingReceipt' },
      { kind: 'packingList' },
      { kind: 'deliveryAcknowledgment' },
      { kind: 'paymentReceipt' },
    ],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00010' },
      { kind: 'waybill', referenceNo: 'WB-010' },
      { kind: 'trip', referenceNo: 'TR-2024-003' },
      { kind: 'truck', referenceNo: 'ر س ط ٣٤٥٦' },
      { kind: 'driver', referenceNo: 'طارق سليمان' },
      { kind: 'deliveryReceipt', referenceNo: 'DR-010' },
      { kind: 'invoice', referenceNo: 'INV-2024-003' },
      { kind: 'paymentReceipt', referenceNo: 'PR-010' },
      { kind: 'settlement', referenceNo: 'SET-2024-001' },
    ],
  },
  {
    id: 11,
    status: 'assigned',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-011' },
      { key: 'shipment', state: 'done', reference: 'SH-011' },
      { key: 'waybill', state: 'current', reference: 'WB-2024-004' },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'شركة الأهرام للإلكترونيات',
      senderPhone: '+201112233445',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'موزع قطري',
      receiverPhone: null,
      destinationCountry: 'قطر',
      destinationCity: 'الدوحة',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'buildingMaterials',
      tripNumber: 'TR-2024-004',
      driverName: 'عبد الله رشاد',
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'مواد غذائية معلبة',
        packageCount: 14,
        pieceCount: 140,
        netWeightKg: 672,
        grossWeightKg: 700,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: 'عبد الله رشاد',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 1220,
      discounts: null,
      finalValue: 1220,
      paid: 0,
      remaining: 1220,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00011' },
      { kind: 'waybill', referenceNo: 'WB-011' },
      { kind: 'trip', referenceNo: 'TR-2024-004' },
      { kind: 'truck', referenceNo: 'ن و ن ٩٠١٢' },
      { kind: 'driver', referenceNo: 'عبد الله رشاد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 12,
    status: 'assigned',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-012' },
      { key: 'shipment', state: 'done', reference: 'SH-012' },
      { key: 'waybill', state: 'current', reference: 'WB-2024-004' },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'ناصر حسن',
      senderPhone: '+201223344556',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'محل الريان',
      receiverPhone: null,
      destinationCountry: 'قطر',
      destinationCity: 'الريان',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'clothing',
      tripNumber: 'TR-2024-004',
      driverName: 'عبد الله رشاد',
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'مستلزمات طبية',
        packageCount: 9,
        pieceCount: 90,
        netWeightKg: 403,
        grossWeightKg: 420,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: 'عبد الله رشاد',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 780,
      discounts: null,
      finalValue: 780,
      paid: 0,
      remaining: 780,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00012' },
      { kind: 'waybill', referenceNo: 'WB-012' },
      { kind: 'trip', referenceNo: 'TR-2024-004' },
      { kind: 'truck', referenceNo: 'ن و ن ٩٠١٢' },
      { kind: 'driver', referenceNo: 'عبد الله رشاد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 13,
    status: 'closed',
    hasShortage: true,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-013' },
      { key: 'shipment', state: 'done', reference: 'SH-013' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-005' },
      { key: 'delivery', state: 'done', reference: 'العجز' },
      { key: 'settlement', state: 'done', reference: 'مغلقة' },
    ],
    summary: {
      senderName: 'مؤسسة الربيع',
      senderPhone: '+201004455667',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'شركة كويتية',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'الكويت',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'electronics',
      tripNumber: 'TR-2024-005',
      driverName: 'يوسف الحناوي',
      currentLocationApprox: 'الكويت',
    },
    packageLines: [
      {
        itemName: 'إلكترونيات',
        packageCount: 22,
        pieceCount: 220,
        netWeightKg: 1056,
        grossWeightKg: 1100,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 20,
        shortageCount: 200,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 448,
      discounts: null,
      finalValue: 448,
      paid: 448,
      remaining: 0,
      collectedByDriver: 179,
      collectionStatus: 'collected',
      collectedByCurrency: [{ amount: 448, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-013-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 448,
          currency: 'KWD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: '2024-01-18 14:00', done: true },
      { label: 'تم التحقق', time: '2024-01-18 18:00', done: true },
      { label: 'مُغلقة', time: '2024-01-19 10:00', done: true },
    ],
    activityLog: [
      {
        message: 'تم تأكيد الدفع وإغلاق الشحنة',
        actor: 'ريم عبد العزيز',
        time: '2026-07-13 12:09',
      },
      { message: 'تم التسليم بعجز 200 قطعة', actor: 'السائق', time: '2026-07-13 12:09' },
      { message: 'تم التحقق من التسليم', actor: 'محمود عبد الحليم', time: '2026-07-13 12:09' },
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [
      { kind: 'receivingReceipt' },
      { kind: 'packingList' },
      { kind: 'deliveryAcknowledgment' },
      { kind: 'paymentReceipt' },
    ],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00013' },
      { kind: 'waybill', referenceNo: 'WB-013' },
      { kind: 'trip', referenceNo: 'TR-2024-005' },
      { kind: 'truck', referenceNo: 'ق ن ز ١١٣٤' },
      { kind: 'driver', referenceNo: 'يوسف الحناوي' },
      { kind: 'deliveryReceipt', referenceNo: 'DR-013' },
      { kind: 'invoice', referenceNo: 'INV-2024-004' },
      { kind: 'paymentReceipt', referenceNo: 'PR-013' },
      { kind: 'settlement', referenceNo: 'SET-2024-002' },
    ],
  },
  {
    id: 14,
    status: 'closed',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-014' },
      { key: 'shipment', state: 'done', reference: 'SH-014' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-005' },
      { key: 'delivery', state: 'done', reference: 'مُسلَّمة' },
      { key: 'settlement', state: 'done', reference: 'مغلقة' },
    ],
    summary: {
      senderName: 'علي الدسوقي',
      senderPhone: '+201115666778',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'متجر الجهراء',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'الجهراء',
      direction: 'return',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'foodstuff',
      tripNumber: 'TR-2024-005',
      driverName: 'يوسف الحناوي',
      currentLocationApprox: 'الجهراء',
    },
    packageLines: [
      {
        itemName: 'ألعاب أطفال',
        packageCount: 11,
        pieceCount: 110,
        netWeightKg: 509,
        grossWeightKg: 530,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 110,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 190,
      discounts: null,
      finalValue: 190,
      paid: 190,
      remaining: 0,
      collectedByDriver: 76,
      collectionStatus: 'collected',
      collectedByCurrency: [{ amount: 190, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-014-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 190,
          currency: 'KWD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: '2024-01-18 14:00', done: true },
      { label: 'تم التحقق', time: '2024-01-18 18:00', done: true },
      { label: 'مُغلقة', time: '2024-01-19 10:00', done: true },
    ],
    activityLog: [
      {
        message: 'تم تأكيد الدفع وإغلاق الشحنة',
        actor: 'ريم عبد العزيز',
        time: '2026-07-13 12:09',
      },
      { message: 'تم التسليم', actor: 'السائق', time: '2026-07-13 12:09' },
      { message: 'تم التحقق من التسليم', actor: 'محمود عبد الحليم', time: '2026-07-13 12:09' },
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [
      { kind: 'receivingReceipt' },
      { kind: 'packingList' },
      { kind: 'deliveryAcknowledgment' },
      { kind: 'paymentReceipt' },
    ],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00014' },
      { kind: 'waybill', referenceNo: 'WB-014' },
      { kind: 'trip', referenceNo: 'TR-2024-005' },
      { kind: 'truck', referenceNo: 'ق ن ز ١١٣٤' },
      { kind: 'driver', referenceNo: 'يوسف الحناوي' },
      { kind: 'deliveryReceipt', referenceNo: 'DR-014' },
      { kind: 'invoice', referenceNo: 'INV-2024-005' },
      { kind: 'paymentReceipt', referenceNo: 'PR-014' },
      { kind: 'settlement', referenceNo: 'SET-2024-002' },
    ],
  },
  {
    id: 15,
    status: 'closed',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-015' },
      { key: 'shipment', state: 'done', reference: 'SH-015' },
      { key: 'waybill', state: 'done', reference: 'WB-2024-005' },
      { key: 'delivery', state: 'done', reference: 'مُسلَّمة' },
      { key: 'settlement', state: 'done', reference: 'مغلقة' },
    ],
    summary: {
      senderName: 'شركة الفجر للملابس الجاهزة',
      senderPhone: '+201226677889',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'موزع حولي',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'حولي',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'furniture',
      tripNumber: 'TR-2024-005',
      driverName: 'يوسف الحناوي',
      currentLocationApprox: 'حولي',
    },
    packageLines: [
      {
        itemName: 'أدوات منزلية',
        packageCount: 16,
        pieceCount: 160,
        netWeightKg: 730,
        grossWeightKg: 760,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 160,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: true,
      confirmedAt: '2024-01-15 07:45',
      driverDisplayName: 'السائق',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 258,
      discounts: null,
      finalValue: 258,
      paid: 258,
      remaining: 0,
      collectedByDriver: 103,
      collectionStatus: 'collected',
      collectedByCurrency: [{ amount: 258, currency: 'EGP' }],
      receiptVouchers: [
        {
          voucherNo: 'RV-015-01',
          date: '2024-01-18',
          method: 'cash',
          receivedBy: 'ريم عبد العزيز',
          amount: 258,
          currency: 'KWD',
        },
      ],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: '2024-01-15 07:45', done: true },
      { label: 'غادرت', time: '2024-01-15 08:00', done: true },
      { label: 'تم التسليم', time: '2024-01-18 14:00', done: true },
      { label: 'تم التحقق', time: '2024-01-18 18:00', done: true },
      { label: 'مُغلقة', time: '2024-01-19 10:00', done: true },
    ],
    activityLog: [
      {
        message: 'تم تأكيد الدفع وإغلاق الشحنة',
        actor: 'ريم عبد العزيز',
        time: '2026-07-13 12:09',
      },
      { message: 'تم التسليم', actor: 'السائق', time: '2026-07-13 12:09' },
      { message: 'تم التحقق من التسليم', actor: 'محمود عبد الحليم', time: '2026-07-13 12:09' },
      { message: 'الشحنة في الطريق', actor: 'النظام', time: '2026-07-13 12:09' },
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [
      { kind: 'receivingReceipt' },
      { kind: 'packingList' },
      { kind: 'deliveryAcknowledgment' },
      { kind: 'paymentReceipt' },
    ],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00015' },
      { kind: 'waybill', referenceNo: 'WB-015' },
      { kind: 'trip', referenceNo: 'TR-2024-005' },
      { kind: 'truck', referenceNo: 'ق ن ز ١١٣٤' },
      { kind: 'driver', referenceNo: 'يوسف الحناوي' },
      { kind: 'deliveryReceipt', referenceNo: 'DR-015' },
      { kind: 'invoice', referenceNo: 'INV-2024-006' },
      { kind: 'paymentReceipt', referenceNo: 'PR-015' },
      { kind: 'settlement', referenceNo: 'SET-2024-002' },
    ],
  },
  {
    id: 16,
    status: 'assigned',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-016' },
      { key: 'shipment', state: 'done', reference: 'SH-016' },
      { key: 'waybill', state: 'current', reference: 'WB-2024-006' },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'أحمد عبد الله',
      senderPhone: '+201001234567',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'شركة بحرينية',
      receiverPhone: null,
      destinationCountry: 'البحرين',
      destinationCity: 'المنامة',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'industrialEquipment',
      tripNumber: 'TR-2024-006',
      driverName: 'إبراهيم سعيد',
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'هدايا وتحف',
        packageCount: 6,
        pieceCount: 60,
        netWeightKg: 240,
        grossWeightKg: 250,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: 'إبراهيم سعيد',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 560,
      discounts: null,
      finalValue: 560,
      paid: 0,
      remaining: 560,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00016' },
      { kind: 'waybill', referenceNo: 'WB-016' },
      { kind: 'trip', referenceNo: 'TR-2024-006' },
      { kind: 'truck', referenceNo: 'م ع د ٧٧٨٩' },
      { kind: 'driver', referenceNo: 'إبراهيم سعيد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 17,
    status: 'assigned',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-017' },
      { key: 'shipment', state: 'done', reference: 'SH-017' },
      { key: 'waybill', state: 'current', reference: 'WB-2024-006' },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'شركة النيل للاستيراد والتصدير',
      senderPhone: '+201112345678',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'وكيل المحرق',
      receiverPhone: null,
      destinationCountry: 'البحرين',
      destinationCity: 'المحرق',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'buildingMaterials',
      tripNumber: 'TR-2024-006',
      driverName: 'إبراهيم سعيد',
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'منسوجات',
        packageCount: 19,
        pieceCount: 190,
        netWeightKg: 864,
        grossWeightKg: 900,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: 'إبراهيم سعيد',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 920,
      discounts: null,
      finalValue: 920,
      paid: 0,
      remaining: 920,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: '2024-01-13 08:00', done: true },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم التعيين لرحلة', actor: 'طارق منصور', time: '2026-07-13 12:09' },
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00017' },
      { kind: 'waybill', referenceNo: 'WB-017' },
      { kind: 'trip', referenceNo: 'TR-2024-006' },
      { kind: 'truck', referenceNo: 'م ع د ٧٧٨٩' },
      { kind: 'driver', referenceNo: 'إبراهيم سعيد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 18,
    status: 'ready',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-018' },
      { key: 'shipment', state: 'current', reference: 'SH-018' },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'سمير عبد الله',
      senderPhone: '+201009988776',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'سمير عبد الله',
      receiverPhone: null,
      destinationCountry: 'مصر',
      destinationCity: 'الإسكندرية',
      direction: 'outbound',
      transportMode: 'land',
      packageType: 'carton',
      goodsCategory: 'clothing',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'مستندات وعينات',
        packageCount: 3,
        pieceCount: 30,
        netWeightKg: 115,
        grossWeightKg: 120,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'EGP',
      priceBeforeDiscount: 9000,
      discounts: null,
      finalValue: 9000,
      paid: 0,
      remaining: 9000,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00018' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 19,
    status: 'ready',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-019' },
      { key: 'shipment', state: 'current', reference: 'SH-019' },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'مؤسسة الدلتا التجارية',
      senderPhone: '+201004567890',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'متجر سعودي',
      receiverPhone: null,
      destinationCountry: 'السعودية',
      destinationCity: 'جدة',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'electronics',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'ملابس رياضية',
        packageCount: 13,
        pieceCount: 130,
        netWeightKg: 624,
        grossWeightKg: 650,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'SAR',
      priceBeforeDiscount: 2692,
      discounts: null,
      finalValue: 2692,
      paid: 0,
      remaining: 2692,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00019' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 20,
    status: 'ready',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-020' },
      { key: 'shipment', state: 'current', reference: 'SH-020' },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'فاطمة إبراهيم',
      senderPhone: '+201115678901',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'موزع إماراتي',
      receiverPhone: null,
      destinationCountry: 'الإمارات',
      destinationCity: 'دبي',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'foodstuff',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'أغذية معلبة',
        packageCount: 27,
        pieceCount: 270,
        netWeightKg: 1296,
        grossWeightKg: 1350,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 1360,
      discounts: null,
      finalValue: 1360,
      paid: 0,
      remaining: 1360,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00020' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 21,
    status: 'draft',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'current', reference: 'SH-021' },
      { key: 'shipment', state: 'pending', reference: null },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'شركة المستقبل للتجارة',
      senderPhone: '+201226789012',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'موزع كويتي',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'الكويت',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'furniture',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'مستحضرات تجميل',
        packageCount: 4,
        pieceCount: 40,
        netWeightKg: 173,
        grossWeightKg: 180,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 110,
      discounts: null,
      finalValue: 110,
      paid: 0,
      remaining: 110,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: null, done: false },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [{ message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' }],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00021' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 22,
    status: 'draft',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'current', reference: 'SH-022' },
      { key: 'shipment', state: 'pending', reference: null },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'خالد عبد الرحمن',
      senderPhone: '+201007890123',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'تاجر الدوحة',
      receiverPhone: null,
      destinationCountry: 'قطر',
      destinationCity: 'الدوحة',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'industrialEquipment',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'قطع غيار سيارات',
        packageCount: 8,
        pieceCount: 80,
        netWeightKg: 365,
        grossWeightKg: 380,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 580,
      discounts: null,
      finalValue: 580,
      paid: 0,
      remaining: 580,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: null, done: false },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [{ message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' }],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00022' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 23,
    status: 'ready',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-023' },
      { key: 'shipment', state: 'current', reference: 'SH-023' },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'مجموعة النصر',
      senderPhone: '+201118901234',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'شركة الرياض',
      receiverPhone: null,
      destinationCountry: 'السعودية',
      destinationCity: 'الرياض',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'buildingMaterials',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'مواد غذائية',
        packageCount: 11,
        pieceCount: 110,
        netWeightKg: 499,
        grossWeightKg: 520,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'SAR',
      priceBeforeDiscount: 2538,
      discounts: null,
      finalValue: 2538,
      paid: 0,
      remaining: 2538,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00023' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 24,
    status: 'draft',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'current', reference: 'SH-024' },
      { key: 'shipment', state: 'pending', reference: null },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'وليد كرم',
      senderPhone: '+201557788990',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'موزع دبي',
      receiverPhone: null,
      destinationCountry: 'الإمارات',
      destinationCity: 'دبي',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'clothing',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'عطور',
        packageCount: 6,
        pieceCount: 60,
        netWeightKg: 278,
        grossWeightKg: 290,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'USD',
      priceBeforeDiscount: 520,
      discounts: null,
      finalValue: 520,
      paid: 0,
      remaining: 520,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: null, done: false },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [{ message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' }],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00024' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
  {
    id: 25,
    status: 'ready',
    hasShortage: false,
    stages: [
      { key: 'receiving', state: 'done', reference: 'SH-025' },
      { key: 'shipment', state: 'current', reference: 'SH-025' },
      { key: 'waybill', state: 'pending', reference: null },
      { key: 'delivery', state: 'pending', reference: null },
      { key: 'settlement', state: 'pending', reference: null },
    ],
    summary: {
      senderName: 'عمر الشناوي',
      senderPhone: '+201001122334',
      warehouseKeeper: 'سلمى عبد الله',
      receiverName: 'موزع كويتي',
      receiverPhone: null,
      destinationCountry: 'الكويت',
      destinationCity: 'الكويت',
      direction: 'outbound',
      transportMode: 'sea',
      packageType: 'carton',
      goodsCategory: 'electronics',
      tripNumber: null,
      driverName: null,
      currentLocationApprox: null,
    },
    packageLines: [
      {
        itemName: 'قرطاسية ومستلزمات مكتبية',
        packageCount: 17,
        pieceCount: 170,
        netWeightKg: 778,
        grossWeightKg: 810,
        dimensionsCm: null,
        volumeM3: null,
        stackable: null,
        fragile: null,
        deliveredCount: 0,
        shortageCount: 0,
      },
    ],
    driverConfirmation: {
      confirmed: false,
      confirmedAt: null,
      driverDisplayName: '—',
    },
    financial: {
      currency: 'KWD',
      priceBeforeDiscount: 252,
      discounts: null,
      finalValue: 252,
      paid: 0,
      remaining: 252,
      collectedByDriver: 0,
      collectionStatus: 'uncollected',
      collectedByCurrency: [],
      receiptVouchers: [],
    },
    timeline: [
      { label: 'تم الإنشاء', time: '2024-01-12 09:00', done: true },
      { label: 'تم الاستلام', time: '2024-01-12 11:00', done: true },
      { label: 'تم التعيين', time: null, done: false },
      { label: 'تأكيد السائق', time: null, done: false },
      { label: 'غادرت', time: null, done: false },
      { label: 'تم التسليم', time: null, done: false },
      { label: 'تم التحقق', time: null, done: false },
      { label: 'مُغلقة', time: null, done: false },
    ],
    activityLog: [
      { message: 'تم الاستلام والوزن', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
      { message: 'تم إنشاء الشحنة', actor: 'سلمى عبد الله', time: '2026-07-13 12:09' },
    ],
    documents: [{ kind: 'receivingReceipt' }, { kind: 'packingList' }],
    docChain: [
      { kind: 'receivingReceipt', referenceNo: 'RR-2024-00025' },
      { kind: 'waybill', referenceNo: 'لم يصدر بعد' },
      { kind: 'trip', referenceNo: 'لم يصدر بعد' },
      { kind: 'truck', referenceNo: 'لم يصدر بعد' },
      { kind: 'driver', referenceNo: 'لم يصدر بعد' },
      { kind: 'deliveryReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'invoice', referenceNo: 'لم يصدر بعد' },
      { kind: 'paymentReceipt', referenceNo: 'لم يصدر بعد' },
      { kind: 'settlement', referenceNo: 'لم يصدر بعد' },
    ],
  },
];
