import { Employee } from './models/employee.model';

/**
 * UI fixtures transcribed from the Shipping Prototype employees list.
 */
export const EMPLOYEE_FIXTURES: readonly Employee[] = [
  {
    id: 1,
    code: 'EMP-001',
    name: 'سلمى عبد الله',
    position: 'موظف مكتب',
    department: 'المستودع',
    phone: '+201001110001',
    netSalary: 10300,
    status: 'active',
    workStatus: null,
    assignedWork: null,
  },
  {
    id: 2,
    code: 'EMP-002',
    name: 'طارق منصور',
    position: 'مدير عمليات',
    department: 'العمليات',
    phone: '+201001110002',
    netSalary: 13000,
    status: 'active',
    workStatus: null,
    assignedWork: null,
  },
  {
    id: 3,
    code: 'DRV-001',
    name: 'يوسف الحناوي',
    position: 'سائق',
    department: 'الأسطول',
    phone: '+201112220001',
    netSalary: 11250,
    status: 'active',
    workStatus: 'onRoad',
    assignedWork: 'TR-2024-001',
  },
  {
    id: 4,
    code: 'DRV-002',
    name: 'حسن المغربي',
    position: 'سائق',
    department: 'الأسطول',
    phone: '+201112220002',
    netSalary: 11700,
    status: 'active',
    workStatus: 'onRoad',
    assignedWork: 'TR-2024-002',
  },
  {
    id: 5,
    code: 'DRV-003',
    name: 'إبراهيم سعيد',
    position: 'سائق',
    department: 'الأسطول',
    phone: '+201112220003',
    netSalary: 11200,
    status: 'active',
    workStatus: 'available',
    assignedWork: null,
  },
  {
    id: 6,
    code: 'DRV-004',
    name: 'طارق سليمان',
    position: 'سائق',
    department: 'الأسطول',
    phone: '+201112220004',
    netSalary: 12100,
    status: 'active',
    workStatus: 'onRoad',
    assignedWork: 'TR-2024-003',
  },
  {
    id: 7,
    code: 'DRV-005',
    name: 'عبد الله رشاد',
    position: 'سائق',
    department: 'الأسطول',
    phone: '+201112220005',
    netSalary: 10900,
    status: 'active',
    workStatus: 'available',
    assignedWork: null,
  },
  {
    id: 8,
    code: 'EMP-003',
    name: 'ريم عبد العزيز',
    position: 'محاسب',
    department: 'المالية',
    phone: '+201001110003',
    netSalary: 11400,
    status: 'active',
    workStatus: null,
    assignedWork: null,
  },
];
